@php
$inputClass='min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-sky-600 focus:ring-2 focus:ring-sky-100';
$imageData=$vehicle->exists ? $vehicle->images->map(fn($image)=>['id'=>$image->id,'url'=>$image->url('small'),'alt_text'=>$image->alt_text,'sort_order'=>$image->sort_order])->values()->all() : [];
$seo=$vehicle->seoMetadata;
@endphp
@if($errors->any())<div class="mb-6 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-800 ring-1 ring-rose-200" role="alert">Please correct the highlighted fields.</div>@endif
<div class="grid min-w-0 gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><div class="min-w-0 space-y-6">
<section class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-6"><h2 class="text-lg font-semibold">Vehicle details</h2><div class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2">
<x-admin.form-field name="title" label="Name" required class="sm:col-span-2"><input id="title" name="title" value="{{ old('title',$vehicle->title) }}" required maxlength="255" class="{{ $inputClass }}"></x-admin.form-field>
<x-admin.form-field name="slug" label="SEO slug" hint="Leave blank to generate automatically."><input id="slug" name="slug" value="{{ old('slug',$vehicle->slug) }}" maxlength="180" class="{{ $inputClass }}"></x-admin.form-field>
<x-admin.form-field name="vehicle_category_id" label="Category" required><select id="vehicle_category_id" name="vehicle_category_id" required class="{{ $inputClass }}"><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('vehicle_category_id',$vehicle->vehicle_category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></x-admin.form-field>
<x-admin.form-field name="summary" label="Short description" class="sm:col-span-2"><textarea id="summary" name="summary" rows="3" maxlength="500" class="{{ $inputClass }}">{{ old('summary',$vehicle->summary) }}</textarea></x-admin.form-field>
<x-admin.form-field name="description" label="Full description" class="sm:col-span-2"><textarea id="description" name="description" rows="8" maxlength="50000" class="{{ $inputClass }}">{{ old('description',$vehicle->description) }}</textarea></x-admin.form-field>
</div></section>
<section class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-6"><h2 class="text-lg font-semibold">Rental details</h2><div class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
<x-admin.form-field name="rental_rate" label="Price" required><input id="rental_rate" name="rental_rate" type="number" min="0" step="0.01" value="{{ old('rental_rate',$vehicle->rental_rate) }}" required class="{{ $inputClass }}"></x-admin.form-field>
<x-admin.form-field name="currency" label="Currency" required><input id="currency" name="currency" value="{{ old('currency',$vehicle->currency ?: 'USD') }}" maxlength="3" required class="{{ $inputClass }} uppercase"></x-admin.form-field>
<x-admin.form-field name="rate_unit" label="Pricing unit" required><select id="rate_unit" name="rate_unit" class="{{ $inputClass }}">@foreach(['hour'=>'Per hour','day'=>'Per day','week'=>'Per week','month'=>'Per month'] as $value=>$label)<option value="{{ $value }}" @selected(old('rate_unit',$vehicle->rate_unit ?: 'day')===$value)>{{ $label }}</option>@endforeach</select></x-admin.form-field>
<x-admin.form-field name="transmission" label="Transmission"><select id="transmission" name="transmission" class="{{ $inputClass }}"><option value="">Not specified</option>@foreach(['automatic'=>'Automatic','manual'=>'Manual'] as $value=>$label)<option value="{{ $value }}" @selected(old('transmission',$vehicle->transmission)===$value)>{{ $label }}</option>@endforeach</select></x-admin.form-field>
<x-admin.form-field name="seats" label="Passengers"><input id="seats" name="seats" type="number" min="1" max="100" value="{{ old('seats',$vehicle->seats) }}" class="{{ $inputClass }}"></x-admin.form-field>
<x-admin.form-field name="luggage_capacity" label="Luggage"><input id="luggage_capacity" name="luggage_capacity" type="number" min="0" max="100" value="{{ old('luggage_capacity',$vehicle->luggage_capacity) }}" class="{{ $inputClass }}"></x-admin.form-field>
<x-admin.form-field name="availability_status" label="Availability" required><select id="availability_status" name="availability_status" required class="{{ $inputClass }}">@foreach($availabilityOptions as $option)<option value="{{ $option->value }}" @selected(old('availability_status',$vehicle->availability_status?->value ?? 'available')===$option->value)>{{ $option->label() }}</option>@endforeach</select></x-admin.form-field>
<label class="flex min-h-11 items-center gap-3 rounded-xl border border-slate-200 px-4 sm:self-end"><input type="hidden" name="has_air_conditioning" value="0"><input type="checkbox" name="has_air_conditioning" value="1" @checked(old('has_air_conditioning',$vehicle->has_air_conditioning))> Air conditioning</label>
<x-admin.form-field name="additional_features" label="Additional features" hint="Add useful rental features or extras. Use a new line for each item." class="sm:col-span-2 lg:col-span-3"><textarea id="additional_features" name="additional_features" rows="5" maxlength="10000" placeholder="Bluetooth audio&#10;Child seat available&#10;Airport pickup" class="{{ $inputClass }}">{{ old('additional_features',$vehicle->additional_features) }}</textarea></x-admin.form-field>
</div></section>
<section class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-6"><h2 class="text-lg font-semibold">Images</h2><p class="mt-1 text-sm text-slate-500">JPEG, PNG, or WebP up to 8 MB. Alt text is required.</p>
@if($vehicle->exists && $imageData)<div x-data="packageExistingImages({{ Js::from($imageData) }})" class="mt-5 space-y-3"><template x-for="(image,index) in items" :key="image.id"><div class="grid gap-3 rounded-xl border border-slate-200 p-3 sm:grid-cols-[96px_minmax(0,1fr)_auto] sm:items-center"><img :src="image.url" :alt="image.alt_text" class="h-24 w-full rounded-lg object-cover sm:w-24"><div><label class="mb-1 block text-sm font-medium">Alt text</label><input :name="`existing_images[${image.id}][alt_text]`" x-model="image.alt_text" required class="{{ $inputClass }}"><input type="hidden" :name="`existing_images[${image.id}][sort_order]`" :value="index"></div><div class="flex flex-wrap gap-2 sm:flex-col"><label class="flex min-h-11 items-center gap-2 text-sm"><input type="radio" name="featured_image_id" :value="image.id" :checked="index===0"> Featured</label><div><button type="button" x-on:click="move(index,-1)" class="size-11 rounded-lg border">↑</button><button type="button" x-on:click="move(index,1)" class="ml-1 size-11 rounded-lg border">↓</button></div><label class="flex min-h-11 items-center gap-2 text-sm text-rose-600"><input type="checkbox" name="delete_image_ids[]" :value="image.id"> Delete</label></div></div></template></div>@endif
<div class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2"><x-admin.form-field name="featured_image" label="New featured image"><input id="featured_image" name="featured_image" type="file" accept="image/jpeg,image/png,image/webp" class="min-h-11 w-full text-sm"></x-admin.form-field><x-admin.form-field name="featured_image_alt" label="Featured image alt text"><input id="featured_image_alt" name="featured_image_alt" value="{{ old('featured_image_alt') }}" maxlength="255" class="{{ $inputClass }}"></x-admin.form-field></div>
<div x-data="packageGalleryUploads()" class="mt-5"><x-admin.form-field name="gallery_images" label="Add gallery images"><input id="gallery_images" name="gallery_images[]" type="file" multiple accept="image/jpeg,image/png,image/webp" x-on:change="select" class="min-h-11 w-full text-sm"></x-admin.form-field><div class="mt-3 space-y-3"><template x-for="(file,index) in files" :key="`${file.name}-${index}`"><div><label class="mb-1 block truncate text-sm font-medium" x-text="`Alt text for ${file.name}`"></label><input :name="`gallery_alt_text[${index}]`" x-model="file.alt" required class="{{ $inputClass }}"></div></template></div></div>
</section>
<section class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-6"><h2 class="text-lg font-semibold">SEO and social sharing</h2><div class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2">
<x-admin.form-field name="seo.meta_title" label="Meta title"><input name="seo[meta_title]" value="{{ old('seo.meta_title',$seo?->meta_title) }}" maxlength="255" class="{{ $inputClass }}"></x-admin.form-field><x-admin.form-field name="seo.canonical_url" label="Canonical URL"><input name="seo[canonical_url]" type="url" value="{{ old('seo.canonical_url',$seo?->canonical_url) }}" maxlength="2048" class="{{ $inputClass }}"></x-admin.form-field><x-admin.form-field name="seo.meta_description" label="Meta description" class="sm:col-span-2"><textarea name="seo[meta_description]" rows="3" maxlength="500" class="{{ $inputClass }}">{{ old('seo.meta_description',$seo?->meta_description) }}</textarea></x-admin.form-field><x-admin.form-field name="seo.og_title" label="Open Graph title"><input name="seo[og_title]" value="{{ old('seo.og_title',$seo?->og_title) }}" maxlength="255" class="{{ $inputClass }}"></x-admin.form-field><x-admin.form-field name="seo.og_image_alt" label="Social image alt text"><input name="seo[og_image_alt]" value="{{ old('seo.og_image_alt',$seo?->og_image_alt) }}" maxlength="255" class="{{ $inputClass }}"></x-admin.form-field><x-admin.form-field name="seo.og_description" label="Open Graph description" class="sm:col-span-2"><textarea name="seo[og_description]" rows="3" maxlength="500" class="{{ $inputClass }}">{{ old('seo.og_description',$seo?->og_description) }}</textarea></x-admin.form-field></div><div class="mt-5 grid gap-3 sm:grid-cols-3"><label class="flex min-h-11 items-center gap-3 rounded-xl border px-4"><input type="hidden" name="seo[robots_index]" value="0"><input type="checkbox" name="seo[robots_index]" value="1" @checked(old('seo.robots_index',$seo?->robots_index ?? true))> Allow indexing</label><label class="flex min-h-11 items-center gap-3 rounded-xl border px-4"><input type="hidden" name="seo[robots_follow]" value="0"><input type="checkbox" name="seo[robots_follow]" value="1" @checked(old('seo.robots_follow',$seo?->robots_follow ?? true))> Follow links</label><label class="flex min-h-11 items-center gap-3 rounded-xl border px-4"><input type="hidden" name="seo_use_featured_image" value="0"><input type="checkbox" name="seo_use_featured_image" value="1" @checked(old('seo_use_featured_image',filled($seo?->og_image_path)))> Use featured image</label></div></section>
</div><aside class="min-w-0 xl:sticky xl:top-28 xl:self-start"><section class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:p-6"><x-admin.form-field name="sort_order" label="Display order" hint="Lower values appear first."><input name="sort_order" type="number" min="0" value="{{ old('sort_order',$vehicle->sort_order ?? 0) }}" required class="{{ $inputClass }}"></x-admin.form-field><div class="mt-5 grid gap-3"><button class="min-h-12 rounded-xl bg-[#082f57] px-5 font-semibold text-white">{{ $submitLabel }}</button><a href="{{ $vehicle->exists ? route('admin.vehicles.show',$vehicle) : route('admin.vehicles.index') }}" class="inline-flex min-h-11 items-center justify-center rounded-xl border border-slate-300 px-4 text-sm font-semibold">Cancel</a></div></section></aside></div>
