<x-public.layout :seo="$seo">
<section class="relative overflow-hidden bg-[#062d50] px-4 py-14 text-white sm:px-6 sm:py-20"><x-public.hero-image :image="data_get($hero, 'image')" :alt="data_get($hero, 'image.alt', $page->title)" class="absolute inset-0 h-full w-full object-cover opacity-25" /><div class="absolute inset-0 bg-gradient-to-r from-[#062d50] via-[#062d50]/90 to-[#062d50]/55"></div><div class="relative mx-auto max-w-7xl"><nav aria-label="Breadcrumb" class="text-sm text-cyan-200"><a href="{{ route('home') }}">Home</a><span aria-hidden="true"> / </span><span aria-current="page">{{ $page->title }}</span></nav><p class="mt-8 text-xs font-bold uppercase tracking-[.24em] text-cyan-300">Island moments</p><h1 class="mt-3 font-display text-4xl font-semibold sm:text-6xl">{{ data_get($hero, 'title') ?: $page->title }}</h1>@if(data_get($hero, 'text') ?: $page->summary)<p class="mt-5 max-w-2xl text-lg leading-8 text-sky-100/75">{{ data_get($hero, 'text') ?: $page->summary }}</p>@endif</div></section>
@if($page->body)<section class="px-4 pt-10 sm:px-6 sm:pt-16 lg:px-8"><div class="rich-content mx-auto max-w-4xl">{!! $page->body !!}</div></section>@endif
<section class="px-4 py-12 sm:px-6 sm:py-20 lg:px-8"><div class="mx-auto max-w-7xl">
@if($albums->isNotEmpty())<nav class="mb-9 flex max-w-full gap-2 overflow-x-auto pb-2" aria-label="Gallery categories"><a href="{{ route('gallery.index') }}" @if(blank($filters['category']??null)) aria-current="page" @endif class="inline-flex min-h-11 shrink-0 items-center rounded-full border px-4 text-sm font-semibold {{ blank($filters['category']??null)?'border-[#082d4f] bg-[#082d4f] text-white':'border-slate-200 bg-white text-[#0a5068]' }}">All</a>@foreach($albums as $album)<a href="{{ route('gallery.index',['category'=>$album->slug]) }}" @if(($filters['category']??null)===$album->slug) aria-current="page" @endif class="inline-flex min-h-11 shrink-0 items-center gap-2 rounded-full border px-4 text-sm font-semibold {{ ($filters['category']??null)===$album->slug?'border-[#082d4f] bg-[#082d4f] text-white':'border-slate-200 bg-white text-[#0a5068]' }}">{{ $album->title }} <span class="opacity-70">{{ $album->images_count }}</span></a>@endforeach</nav>@endif
@if($images->isEmpty())<div class="rounded-[2rem] border border-dashed border-slate-300 bg-white px-6 py-20 text-center"><h2 class="font-display text-2xl font-semibold text-[#082d4f]">No published photographs yet</h2><p class="mt-2 text-slate-600">Please check back after new gallery images are published.</p>@if(filled($filters['category']??null))<a href="{{ route('gallery.index') }}" class="mt-6 inline-flex min-h-11 items-center rounded-full bg-[#082d4f] px-5 font-semibold text-white">View all photographs</a>@endif</div>
@else<div class="columns-1 gap-5 sm:columns-2 lg:columns-3">@foreach($images as $image)<figure class="mb-5 break-inside-avoid overflow-hidden rounded-[1.5rem] bg-white shadow-sm ring-1 ring-slate-200"><button type="button" data-gallery-preview data-full-image="{{ $image->url() }}" data-image-alt="{{ $image->alt_text }}" data-image-title="{{ $image->title }}" data-image-caption="{{ $image->caption }}" class="block min-h-11 w-full cursor-zoom-in overflow-hidden bg-slate-100 text-left focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-cyan-500"><img src="{{ $image->url('medium') }}" srcset="{{ $image->url('small') }} 480w, {{ $image->url('medium') }} 960w, {{ $image->url() }} 1800w" sizes="(min-width:1024px) 33vw, (min-width:640px) 50vw, 100vw" alt="{{ $image->alt_text }}" width="{{ $image->width }}" height="{{ $image->height }}" loading="lazy" decoding="async" class="h-auto w-full object-contain"></button>@if($image->title || $image->caption)<figcaption class="p-4 sm:p-5">@if($image->title)<h2 class="font-display text-lg font-semibold text-[#082d4f]">{{ $image->title }}</h2>@endif @if($image->caption)<p class="mt-1 text-sm leading-6 text-slate-600">{{ $image->caption }}</p>@endif</figcaption>@endif</figure>@endforeach</div><div class="mt-10">{{ $images->onEachSide(1)->links() }}</div>@endif
</div></section>
<dialog data-gallery-dialog aria-labelledby="gallery-dialog-title" class="m-auto max-h-[calc(100svh-2rem)] w-[calc(100%-2rem)] max-w-6xl overflow-hidden rounded-2xl bg-[#041f37] p-0 text-white shadow-2xl backdrop:bg-slate-950/85"><div class="flex max-h-[calc(100svh-2rem)] flex-col"><div class="flex items-start justify-between gap-4 p-3 sm:p-4"><div class="min-w-0"><h2 id="gallery-dialog-title" data-gallery-dialog-title class="break-words font-display text-lg font-semibold"></h2><p data-gallery-dialog-caption class="mt-1 break-words text-sm text-sky-100/75"></p></div><button type="button" data-gallery-close class="inline-flex size-11 shrink-0 items-center justify-center rounded-full border border-white/30 text-2xl" aria-label="Close image preview">×</button></div><div class="min-h-0 flex-1 overflow-auto p-3 pt-0 sm:p-4 sm:pt-0"><img data-gallery-dialog-image src="" alt="" class="mx-auto max-h-[calc(100svh-8rem)] h-auto max-w-full object-contain"></div></div></dialog>
</x-public.layout>
