<x-admin.layout :title="$package->title" eyebrow="Packages">
    <div class="mb-6 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div class="min-w-0"><a href="{{ route('admin.packages.index') }}" class="inline-flex min-h-11 items-center text-sm font-semibold text-sky-700">← Back to packages</a><h2 class="break-words text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">{{ $package->title }}</h2><p class="mt-2 break-all text-sm text-slate-500">/tour-packages/{{ $package->slug }}</p></div>
        <div class="flex flex-wrap gap-2"><a href="{{ route('admin.packages.edit', $package) }}" class="inline-flex min-h-11 items-center justify-center rounded-xl bg-[#082f57] px-5 text-sm font-semibold text-white">Edit package</a></div>
    </div>

    @if (session('success'))<div class="mb-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800 ring-1 ring-emerald-200" role="status">{{ session('success') }}</div>@endif
    @if ($errors->any())<div class="mb-5 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-800 ring-1 ring-rose-200" role="alert">{{ $errors->first() }}</div>@endif

    <div class="grid min-w-0 gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
        <div class="min-w-0 space-y-6">
            <section class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200">
                @if ($package->images->first())<img src="{{ $package->images->first()->url() }}" srcset="{{ $package->images->first()->url('small') }} 480w, {{ $package->images->first()->url('medium') }} 960w, {{ $package->images->first()->url() }} 1600w" sizes="(min-width: 1280px) calc(100vw - 700px), 100vw" alt="{{ $package->images->first()->alt_text }}" class="aspect-[16/9] w-full object-cover" width="1600" height="900">@endif
                <div class="p-5 sm:p-7"><div class="flex flex-wrap gap-2"><span class="rounded-full bg-sky-50 px-3 py-1 text-sm font-medium text-sky-700">{{ $package->availability_status->label() }}</span><span class="rounded-full bg-slate-100 px-3 py-1 text-sm capitalize text-slate-700">{{ $package->status->value }}</span>@if ($package->is_featured)<span class="rounded-full bg-amber-50 px-3 py-1 text-sm font-medium text-amber-700">Featured</span>@endif</div><p class="mt-5 whitespace-pre-line leading-7 text-slate-700">{{ $package->description ?: 'No full description has been added.' }}</p></div>
            </section>

            <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h3 class="text-lg font-semibold text-slate-950">Itinerary</h3><div class="mt-5 space-y-4">@forelse ($package->itineraries as $item)<article class="grid gap-3 rounded-xl border border-slate-200 p-4 sm:grid-cols-[80px_1fr]"><div class="font-semibold text-sky-700">Day {{ $item->day_number }}</div><div class="min-w-0"><h4 class="break-words font-semibold text-slate-900">{{ $item->title }}</h4><p class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-600">{{ $item->description }}</p></div></article>@empty<p class="text-sm text-slate-500">No itinerary has been added.</p>@endforelse</div></section>

            <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h3 class="text-lg font-semibold text-slate-950">Gallery</h3><div class="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">@forelse ($package->images as $image)<figure class="min-w-0 overflow-hidden rounded-xl border border-slate-200"><img src="{{ $image->url('medium') }}" alt="{{ $image->alt_text }}" loading="lazy" class="aspect-[4/3] w-full object-cover" width="960" height="720"><figcaption class="break-words p-3 text-xs text-slate-500">{{ $image->alt_text }}</figcaption></figure>@empty<p class="text-sm text-slate-500 sm:col-span-2">No images uploaded.</p>@endforelse</div></section>

            <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200 sm:p-7"><h3 class="text-lg font-semibold text-slate-950">SEO</h3><dl class="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt class="font-medium text-slate-500">Meta title</dt><dd class="mt-1 break-words text-slate-800">{{ $package->seoMetadata?->meta_title ?: 'Uses package title' }}</dd></div><div><dt class="font-medium text-slate-500">Robots</dt><dd class="mt-1 text-slate-800">{{ $package->seoMetadata?->robots_index === false ? 'No index' : 'Index' }}, {{ $package->seoMetadata?->robots_follow === false ? 'no follow' : 'follow' }}</dd></div><div class="sm:col-span-2"><dt class="font-medium text-slate-500">Meta description</dt><dd class="mt-1 break-words text-slate-800">{{ $package->seoMetadata?->meta_description ?: 'Not set' }}</dd></div><div class="sm:col-span-2"><dt class="font-medium text-slate-500">Canonical</dt><dd class="mt-1 break-all text-slate-800">{{ $package->seoMetadata?->canonical_url ?: 'Generated automatically' }}</dd></div></dl></section>
        </div>

        <aside class="min-w-0 space-y-5 xl:sticky xl:top-28 xl:self-start">
            <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 class="font-semibold text-slate-950">Package summary</h3><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-slate-500">Destination</dt><dd class="break-words text-right font-medium">{{ $package->destination ?: '—' }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Duration</dt><dd class="font-medium">{{ $package->duration_days }} days</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Starting price</dt><dd class="font-medium">{{ $package->starting_price !== null ? $package->currency.' '.number_format((float) $package->starting_price, 2) : 'On request' }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Inquiries</dt><dd class="font-medium">{{ $package->inquiry_details_count }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Order</dt><dd class="font-medium">{{ $package->sort_order }}</dd></div></dl></section>

            <section class="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h3 class="font-semibold text-slate-950">Publishing</h3><div class="mt-4 grid gap-3"><form method="POST" action="{{ route('admin.packages.status', $package) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $package->status === App\Enums\PublicationStatus::Published ? 'draft' : 'published' }}"><button class="min-h-11 w-full rounded-xl bg-emerald-700 px-4 text-sm font-semibold text-white">{{ $package->status === App\Enums\PublicationStatus::Published ? 'Move to draft' : 'Publish package' }}</button></form><form method="POST" action="{{ route('admin.packages.status', $package) }}">@csrf @method('PATCH')<input type="hidden" name="is_featured" value="{{ $package->is_featured ? 0 : 1 }}"><button class="min-h-11 w-full rounded-xl border border-amber-300 px-4 text-sm font-semibold text-amber-800">{{ $package->is_featured ? 'Remove featured status' : 'Feature package' }}</button></form></div></section>

            @can('delete', $package)<section class="rounded-2xl border border-rose-200 bg-rose-50 p-5"><h3 class="font-semibold text-rose-900">Delete package</h3><p class="mt-2 text-sm leading-6 text-rose-700">Deletion is blocked when inquiry history exists.</p><form method="POST" action="{{ route('admin.packages.destroy', $package) }}" class="mt-4" onsubmit="return confirm('Delete this package permanently?')">@csrf @method('DELETE')<button class="min-h-11 w-full rounded-xl border border-rose-300 px-4 text-sm font-semibold text-rose-800">Delete permanently</button></form></section>@endcan
        </aside>
    </div>
</x-admin.layout>
